
WITH CTE AS (SELECT P.PASSENGER_ID, MIN(B.ARRIVAL_TIME) AS MIN_BUS_TIME 
FROM BUSES B INNER JOIN PASSENGERS P 
ON P.ARRIVAL_TIME <= B.ARRIVAL_TIME 
GROUP BY P.PASSENGER_ID)

SELECT B.BUS_ID AS BUS_ID, IFNULL(COUNT(P.PASSENGER_ID), 0) PASSENGERS_CNT 
FROM BUSES B LEFT JOIN CTE P 
ON MIN_BUS_TIME = B.ARRIVAL_TIME 
GROUP BY B.BUS_ID ORDER BY 1

